version: '3.8'

services:
  mongodb:
    image: mongo:latest
    # Remove the port mapping for MongoDB
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    command: mongod --bind_ip_all

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5090:5090"  # Changed back to 5090
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/orrery_db?authSource=admin
      - JWT_SECRET=your_secret_key_here

volumes:
  mongodb_data: