version: '3.8'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    command: mongod --bind_ip_all
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5090:5090"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017/orrery_db?authSource=admin
      - JWT_SECRET=your_secret_key_here
      - NASA_API_KEY=WxfeB2yJCLFtQMOp0Atbpj77LP0LYTFMf3HLUBpH
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: